from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import config
import local_calendar_backend
import scheduler
import state_store
import utils
from calendar_repository import CalendarRepository
from molly_core import MollyCore
from molly_core_requests import resolution_from_request


OUTPUT_PATH = ROOT / "docs" / "jeeyoung_verification_latest.md"


def _reset_paths(tmpdir: str) -> None:
    config.CALENDAR_BACKEND = "local"
    config.LOCAL_CALENDAR_DB_PATH = Path(tmpdir) / "local_calendar.db"
    config.STATE_DB_PATH = Path(tmpdir) / "molly_state.db"


def _seed(repo: CalendarRepository) -> None:
    service = repo.service
    # Mixed calendars for upcoming verification
    local_calendar_backend.add_event(service, {
        "calendar": "family",
        "title": "Family dinner",
        "date": utils.parse_date("21-04-2026"),
        "start": "18:00",
        "end": "19:00",
    })
    local_calendar_backend.add_event(service, {
        "calendar": "younha",
        "title": "Piano",
        "date": utils.parse_date("21-04-2026"),
        "start": "16:00",
        "end": "17:00",
    })
    local_calendar_backend.add_event(service, {
        "calendar": "sunghwan",
        "title": "Dentist",
        "date": utils.parse_date("22-04-2026"),
        "start": "09:00",
        "end": "10:00",
    })
    # Wrong-calendar event for move verification
    local_calendar_backend.add_event(service, {
        "calendar": "family",
        "title": "Sutton mock test",
        "date": utils.parse_date("17-05-2026"),
        "start": "13:30",
        "end": "15:40",
    })
    # Reminder override verification
    local_calendar_backend.add_event(service, {
        "calendar": "younha",
        "title": "Cubs",
        "date": utils.parse_date("13-04-2026"),
        "start": "18:30",
        "end": "20:00",
        "recurrence": ["RRULE:FREQ=WEEKLY;BYDAY=MO"],
    })
    local_calendar_backend.set_recurring_occurrence_override(
        service,
        "younha",
        "Cubs",
        utils.parse_date("20-04-2026"),
        changes={"title": "Cubs @ Green Lane Primary School"},
        metadata={
            "location": "Green Lane Primary School, Green Lane, Worcester Park KT4 8AS",
            "notes": "This week only, not Scout Centre. Enter via the double gates.",
        },
    )


def _execute(core: MollyCore, payload: dict) -> str:
    resolution = resolution_from_request(payload)
    return core.execute_resolution(resolution)


def main() -> None:
    with tempfile.TemporaryDirectory(prefix="molly-jeeyoung-") as tmpdir:
        _reset_paths(tmpdir)
        state_store.init_db()
        repo = CalendarRepository.from_config()
        core = MollyCore(repo)
        _seed(repo)

        upcoming_payload = {
            "action": "view",
            "scope": "upcoming",
            "limit": 10,
            "raw_input": "Show me upcoming",
        }
        upcoming_message = _execute(core, upcoming_payload)

        move_payload = {
            "action": "move_event",
            "source_calendar": "family",
            "target_calendar": "Younha",
            "title": "Sutton mock test",
            "target_date": "2026-05-17",
            "raw_input": "not family, change to Younha",
        }
        move_message = _execute(core, move_payload)
        younha_after_move = _execute(core, {
            "action": "view",
            "scope": "upcoming",
            "target_calendar": "younha",
            "limit": 20,
            "raw_input": "show upcoming YounHa",
        })

        cubs = [
            ev for ev in repo.list_events(utils.parse_date("20-04-2026"))
            if "cubs" in ev.get("summary", "").lower()
        ][0]
        start_dt = utils.TZ.localize(__import__("datetime").datetime(2026, 4, 20, 18, 30))
        reminder_text = scheduler._format_reminder_text(cubs, start_dt, 60)

        lines = [
            "# JeeYoung verification, latest build",
            "",
            "This file is generated by `scripts/verify_jeeyoung_cases.py`.",
            "",
            "## 1) Show me upcoming",
            "",
            "Request payload:",
            "```json",
            json.dumps(upcoming_payload, ensure_ascii=False, indent=2),
            "```",
            "",
            "Response:",
            "```",
            upcoming_message,
            "```",
            "",
            "## 2) not family, change to Younha",
            "",
            "Request payload:",
            "```json",
            json.dumps(move_payload, ensure_ascii=False, indent=2),
            "```",
            "",
            "Response:",
            "```",
            move_message,
            "```",
            "",
            "YounHa after move:",
            "```",
            younha_after_move,
            "```",
            "",
            "## 3) Reminder override preview for Cubs",
            "",
            "Expected reminder text now:",
            "```",
            reminder_text,
            "```",
        ]
        OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(OUTPUT_PATH)


if __name__ == "__main__":
    main()
